language: python
python:
  - "3.5"
sudo: required
install: "pip install lxml html5lib bs4 pandas pytest requests selenium"
script: "py.test"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver